import type { Metadata } from "next";
import { Inter , Commissioner } from "next/font/google";
import "./globals.scss";
import "./icon.css"
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const geistInter = Inter({
    variable: "--font-geist-Inter",
    subsets: ["latin"],
});
const geistCommissioner = Commissioner({
    variable: "--font-geist-Commissioner",
    subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Escort Crush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistInter.variable} ${geistCommissioner.variable} `}>
      <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
